### ISSUE TITLE
Trying to sign transactions for BSC

### ISSUE THREAD

**Issue by bosswhale** [rumblefishdev/eth-signer-kms#19]
Hello,
Thanks for your provider, exactly what i was looking for but...
I'm trying to sign transaction for BSC Testnet but it crashes with the following message :
```
Starting migrations...
======================
> Network name:    'testnet'
> Network id:      97
> Block gas limit: 30000000 (0x1c9c380)


1_deploy_contracts.js
=====================

   Replacing 'ContractExample'
   -----------------------

Error:  *** Deployment Failed ***

"ContractExample" -- Chain with ID 97 not supported.
```
Here is my configuration in truffle-config.js :
```
    testnet: {
      provider: () => new KMSProvider({
        keyId: process.env.KEYID,
        providerOrUrl: "https://data-seed-prebsc-1-s1.binance.org:8545"
      }),
      network_id: 97,
      confirmations: 10,
      timeoutBlocks: 200,
      skipDryRun: false
    },
```

Note : the exact HDWalletProvider configuration (with a mnemonic) works like a charm. Steps with AWS configuration, KMS access  seems to be ok (i have succeed to get ETH address with https://github.com/lucashenning/aws-kms-ethereum-signing script).
``` 
   testnet: {
      provider: () => new HDWalletProvider({
        mnemonic: mnemonic, 
        providerOrUrl: "https://data-seed-prebsc-1-s1.binance.org:8545"
      }),
      network_id: 97,
      confirmations: 10,
      timeoutBlocks: 200,
      skipDryRun: false
    },
```
Config :
Node v12.18.0
Truffle v5.3.12
eth-signer-kms v1.2.0

Do you have any clue? A missing config perhaps?

Thanks in advance!

**Comment by kowalski** [comment]
With 2.0 released it no longer requires passing parameters for `Common` object. You should be able to use it with binance without a problem now.
